### ISSUE TITLE
False positive for UseMultipartAlternativeAsContentTypeOfEmailCheck

### ISSUE THREAD

**Issue by schasse** [flyerhzm/rails_best_practices#196]
Hi,

I have got the following setup of email templates

```
template.html.haml
template.en.text.haml
template.de.text.haml
```

content type in email headers is as expected 'multipart/alternative', but ther check says that you should use multipart/alternative as content_type of email.

EDIT:
I just updated rails_best_practices to version 0.4.4 and can still confirm that false positive.

**Comment by okolomoets** [comment]
Hi, 
This issue is still reproducible for me. 

My current version of `rails_best_practices` is `1.19.4`
