### ISSUE TITLE
Proposal: Drop Rails 2 support

### ISSUE THREAD

**Issue by andyw8** [flyerhzm/rails_best_practices#246]
I see there are a number of places in the code which cover Rails 2.

What do you think about dropping support for this old version?

**Comment by Loremaster** [comment]
+1

**Comment by tibbon** [comment]
+1

**Comment by oliverklee** [comment]
:+1:

**Comment by dennisvandehoef** [comment]
+1

**Comment by mada41** [comment]
👍  cc @flyerhzm

**Comment by andyw8** [comment]
I've made a start on this: https://github.com/flyerhzm/rails_best_practices/pull/294
