### ISSUE TITLE
Problem with search_data method in model labelled as unused!

### ISSUE THREAD

**Issue by cdrrazan** [flyerhzm/rails_best_practices#352]
Upon running and executing rails_best_practices, it labels `search_data` as unused model method whereas `search_data` is used from **searchkick** to control the type of indexing. 

```
  def search_data
    attributes.merge(
      group_id: groups.try(:ids)
    )
  end
```

This should be ignored!

**Comment by arieliten** [comment]
@cdrrazan You can fix it by adding those methods in the proper `config/rails_best_practices.yml` file. In my case, I updated that file with:
```yaml
RemoveUnusedMethodsInModelsCheck: { except_methods: ['User#search_data'] }
```
and then it passed. Hope it helps
