### ISSUE TITLE
Add support for Ruby 3.1 shorthand hash syntax

### ISSUE THREAD

**Issue by nickjer** [flyerhzm/rails_best_practices#388]
Ruby 3.1 has a new shorthand for its hash syntax. So you can now do things like...

```ruby
def create
  @my_model = MyModel.new(value:)
  # ...
end

def value
  'value'
end
```

Unfortunately, for the above scenario I get the following linter warning `remove unused methods (MyController#value)` even though the method `#value` is being used.

**Comment by flyerhzm** [comment]
@nickjer it's fixed in version 1.23.0
