### ISSUE TITLE
Rails 7 Support

### ISSUE THREAD

**Issue by KieranP** [flyerhzm/rails_best_practices#389]
Latest release locked down the gem to Rails 6.1.

https://github.com/flyerhzm/rails_best_practices/commit/6375208777871973f4e60d77c27cb1ac903a61f2#diff-e34e857bccadd4d7d455a0b69ef259eab0a791cfaca900405478fc49c3f8cf0e

As such, my Rails 7 app is stuck on 1.22.1 when that restriction didn't exist.

**Comment by flyerhzm** [comment]
@KieranP okay, it's fixed in version 1.23.1
